export const LocalDetails= [
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs046",
        "name": "Edwin",
        "passoutyear": 2024,
        "arrears": 3,
        "sgpa": 34.5,
    },
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs033",
        "passoutyear": 2023,
        "name": "Sarah",
        "arrears": 4,
        "sgpa": 44.5,
    },
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs003",
        "passoutyear": 2024,
        "name": "Samuel",
        "arrears": 0,
        "sgpa": 47.5,
    },
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs026",
        "name": "Gregory",
        "passoutyear": 2022,
        "arrears": 5,
        "sgpa": 54.5,
    },
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs013",
        "name": "Edwin",
        "passoutyear": 2023,
        "arrears": 3,
        "sgpa": 34.5,
    },
    {
        "picture": "https://via.placeholder.com/150/92c952",
        "username": "jec20cs036",
        "name": "Nithin",
        "passoutyear": 2024,
        "arrears": 0,
        "sgpa": 72.5,
    },
]