export const LocalDetails= [
    {
        "placementid": 1234,
        "username": "jec20cs046",
        "status": "applied",
        "name": "Edwin",
        "resume": null,
    },
    {
        "placementid": 1234,
        "username": "jec20cs010",
        "status": "applied",
        "name": "Sarah",
        "resume": null,
    },
    {
        "placementid": 9090,
        "username": "jec20cs005",
        "status": "applied",
        "name": "Samuel",
        "resume": null,
    },
    {
        "placementid": 5678,
        "username": "jec20cs028",
        "status": "applied",
        "name": "Gregory",
        "resume": null,
    },
    {
        "placementid": 1234,
        "username": "jec20cs034",
        "status": "applied",
        "name": "Aswin",
        "resume": null,
    },
    {
        "placementid": 5678,
        "username": "jec20cs076",
        "status": "applied",
        "name": "Hazel",
        "resume": null,
    },
    {
        "placementid": 9090,
        "username": "jec20cs064",
        "status": "applied",
        "name": "Ken",
        "resume": null,
    },
    {
        "placementid": 9090,
        "username": "jec20cs035",
        "status": "applied",
        "name": "Augustin",
        "resume": null,
    },
]